use unordered_map instead of map for sake of speed
an also hopefully to avoid a FTBFS on travis:

/home/travis/build/simgrid/simgrid/src/smpi/private.hpp:13:36: error:
  wrong number of template arguments (2, should be 4)

/usr/include/boost/detail/container_fwd.hpp:132:73: error: provided
  for ‘template<class Key, class T, class Compare, class Allocator>
  class std::map’