Size can be negative.  Use ssize_t instead of size_t.
Error caught by Clang:
In file included from /home/giersch/lsrc/simgrid/simgrid-git/src/xbt/mmalloc/mm.c:21:
src/xbt/mmalloc/mmorecore.c:74:19: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
  } else if (size < 0) {