Use function-like macros instead of inline functions for MC_is_active().
When using functions, Gcc apparently does not remove dead branches when
building without optimizations, and then complains at link time with:

Linking C executable ../../bin/gras_stub_generator
../../lib/libsimgrid.so.3.8: error: undefined reference to 'MC_ignore'
../../lib/libsimgrid.so.3.8: error: undefined reference to 'MC_do_the_modelcheck_for_real'
../../lib/libsimgrid.so.3.8: error: undefined reference to 'MC_process_clock_get'
../../lib/libsimgrid.so.3.8: error: undefined reference to 'MC_process_clock_add'
../../lib/libsimgrid.so.3.8: error: undefined reference to 'MC_memory_init'
../../lib/libsimgrid.so.3.8: error: undefined reference to 'MC_new_stack_area'
collect2: error: ld returned 1 exit status

This is if course when building with -Denable_model-checking=OFF.